use_frameworks!

platform :ios, '8.0'

target 'UIView-Position_Example' do
  pod 'UIView-Position', :path => '../'

  target 'UIView-Position_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
